// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qugpppcixjgtxdjrnwft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Z3BwcGNpeGpndHhkanJud2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1OTU5MjgsImV4cCI6MjA3NDE3MTkyOH0.LheUGdLA91QDrcEVUhEOXmeBIiS0tKLrN5H8kF9a9EE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});